version: '3'
services:

  heavydb:
    image: ${HEAVYDB_DOCKER_IMAGE}
    ports:
      - 6273:6273
      - 6274:6274
      - 6278:6278
      - 6279:6279
    volumes:
      - ./.heavyai/heavyai.conf:/heavyai-storage/heavyai.conf