version: '3'
services:

  omniscidb:
    image: omnisci/core-os-cpu:v5.5.0
    ports:
      - 6273:6273
      - 6274:6274
      - 6278:6278
      - 6279:6279
    volumes:
      - ./.omnisci/omnisci.conf:/omnisci-storage/omnisci.conf