#
# Usage:
#   conda env create --file=.conda/environment.yml -n rbc-dev
#   python setup.py develop
#   pytest -sv .

name: rbc
channels:
  - conda-forge
  - numba
  - defaults
dependencies:
  - python>=3.7
  - setuptools
  - numba>=0.52
  - llvmlite
  - pytest
  - tblib
  - thriftpy2
  - netifaces
  - clang=10
  - clangxx=10
  - six
  - cffi
  # - cudatoolkit-dev   # disable temporary
